### ISSUE TITLE
Rails Integration

### ISSUE THREAD

**Issue by GUI** [bdurand/secret_keys#10]
This is more of just a heads up and thank you, but I wanted to let you know that I built a little gem on top of SecretKeys for tighter Rails integration: https://github.com/GUI/secret_keys_rails

The rails integration doesn't necessarily do a lot, so SecretKeys is definitely to thank for all the heavy lifting. The integration mostly just makes some assumptions to make the developer experience in Rails a bit more automatic and roughly match how the default Rails encrypted credentials work.

If you were looking to include any tighter Rails integration into secret_keys itself, I'm happy to scrap my gem or collaborate however you all best see fit. Otherwise, I'm happy to keep the Rails integration gem separate and we can close this issue. But just thought I'd drop a note here in case others might find this useful and to hopefully prevent any duplicate efforts.

SecretKeys definitely scratches a bit of an itch for how I've personally wished encrypted credentials worked in Rails since they were introduced, so thank you for providing this nice library.

**Comment by R167** [comment]
Sounds good! We're going through and fixing a couple things right now: splitting out the raw encryption logic from being class methods, adding in the CLI, etc. Should hopefully have a stable API pretty soon, though from a quick glance, it _shouldn't_ break any of what you've been building.

Totally happy to have someone else building the railtie separately, which is probably a good design to have separate to reduce dependencies of the core code. We've been using this for a rails deployment, though with some slightly different requirements like `{api_user: "plaintext value", api_password: "<encrypted_value>"}`, so needed something a bit more fine-grained.

Glad to find someone else if finding it useful!

And, cause we're really curious, how did you come across this repo before we even published the gem 😄 ?

**Comment by GUI** [comment]
Hah, yeah, sorry if I stumbled upon this earlier than you all were expecting. :) I found it on a deep-dive GitHub search of Ruby projects that dealt with encrypted secrets. I happened upon this project, and it fit what I had been looking for, but hadn't really been able to find otherwise. Yay of open source! But I definitely understand that this is a pre-release and you all may still be working on things. So don't let me building on top of it pressure you into any type of design decisions or feeling like you need to maintain compatibility at this stage. I can update accordingly if you decide to make any changes.

And regarding the Rails integration, while I took the approach of mirroring how Rails own encrypted credentials worked (where it assumes the entire file is encrypted for editing purposes), the Railtie should still work for loading a file that's of a mixed nature with both encrypted and unencrypted values (you'd just have to be using the underlying `secret_keys` command to manage that file). I had focused on documenting that Rails-like usage and editing workflow (and focusing more on the git-friendly encrypted format), but I could also flush out other documentation on how to use the Railtie for integrating those type of mixed encrypted/non-encrypted files.

**Comment by R167** [comment]
Great to hear @GUI! Glad to hear we were solving a problem you ran into as well. As a heads up, we should be just about ready to push `1.0.0`, and (to my knowledge) everything should be backwards compatible. We made a couple minor changes you should be aware of though:

- salt now defaults to 16 bytes (old files are fine)
- there is now a `".version"` key on encrypted files so if we ever need to break something (e.g. increase `KDF_ITERATIONS`), we can know that either:
  - the current gem version doesn't support reading a file from the future
  - we need to use an old decryption routine for this file

Everything else should would just about the same. We moved some logic around to direct access to `SecretKeys::Encryptor` if you have a use case for "I just need to encrypt a payload and don't want to deal with OpenSSL directly", etc. with sane defaults.

**Comment by R167** [comment]
Heads up @GUI: v1.0.1 is released
