### ISSUE TITLE
Proposed command line specification

### ISSUE THREAD

**Issue by bdurand** [bdurand/secret_keys#4]
secret_keys command

secret_keys command -s/--secret=foo
secret_keys command --secret-file=/secrets/file
echo 'foo' | secret_keys command --secret-stdin

- as file is STDIN

secret_keys encrypt -f/--format=json (argument error if don't match) filein [fileout]

secret_keys decrypt options /file

secret_keys read --key=name /file

secret_keys edit /file --set-encrypted key=value --set-decrypted key=value --remove key (-e, -d, -r)

keys cannot have dots or equals in command args and values can only be strings

secret_keys decrypt [options] <filein> [fileout|-]

global options

--secret -s (default -)
--secret-file
--format -f
filein
fileout|-

read options

--key

encrypt option

-

decrypt options

-

edit options

--set-encrypted -e
--set-decrypted -d
--remove -r

Ex:
curl blah.com | secret_keys decrypt -

**Comment by R167** [comment]
Resolved with #9
